# Site settings
title: Abr9h9m Personal Portfolio 
email: your-email@domain.com
url: https://abr9h9m.github.io/Abr9h9m-.github.io
description: "This Webiste will have information about myself."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: SGX3 2025

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Abr9h9m

# Build settings
markdown: kramdown
permalink: pretty
